### ISSUE TITLE
The status bar only displays a circle with two small lines aside

### ISSUE THREAD

**Issue by boxstart** [waderyan/vscode-gitblame#11]
Using vscode insider edition (2016-07-14), only a small circle with two small lines aside is displayed. On hover it shows tooltip 'git blame'. Clicking on the status bar does not invoke any action.

Note aside: the git blame extension never worked on this machine, so I'm not quite sure if the system meets the requirements.

**Comment by martellaj** [comment]
I noticed after updating Code that the extension wasn't working for me either. I simply uninstalled/reinstalled the extension and it's working properly now. If you haven't tried that yet, I'd suggest giving that a go.

**Comment by boxstart** [comment]
Unfortunately, a fresh install didn't solve my problem. Is there a location where I could find an error log (if one exists)?

**Comment by boxstart** [comment]
I debugged the extension and found out that the path to the Git executable was not in my path settings. Adding the following to settings.json didn't work.

```
// Path to the git executable
"git.path": "C:\\Program Files\\Git\\bin\\git"
```

Only after adding git to the path (windows system) the blame info appeared in vscode. The problem is solved, but the extension might be enhanced to display relevant error information.
