### ISSUE TITLE
Show GIT SHA from Commit

### ISSUE THREAD

**Issue by coleGillespie** [waderyan/vscode-gitblame#3]
Is this possible? Also would be nice to right click copy the sha of the commit

**Comment by waderyan** [comment]
Yeah this is possible. I'll look into adding this on the next release. thanks for the feedback.

**Comment by coleGillespie** [comment]
happy to help. will look into the code.

**Comment by joaomoreno** [comment]
I would love to get this!

**Comment by isidorn** [comment]
Yes, I would also need this.

**Comment by budajeff** [comment]
I'd like to see the git SHA so that I could copy/paste it into other tools to view the content of the commit. Thanks.

**Comment by waderyan** [comment]
I like this idea. Added to the backlog.

**Comment by nonameolsson** [comment]
Very good feature!

**Comment by martellaj** [comment]
I think you can mark this as closed (with PR #12). Great addition!
