### ISSUE TITLE
Too many options for gitblame

### ISSUE THREAD

**Issue by jose-a-sa** [waderyan/vscode-gitblame#32]
I have seen that this extension has of today 84 possible settings.
I think it is time for a GUI tab with all the essential options (with checkboxes, dropdowns and so on) plus a a advanced section because the options are too crowded.

**Comment by Sertion** [comment]
Hey José.

This extension currently have 8 available configurations. I am planning to clean up the readme but perhaps you want to direct this issue to a different extension?
