### ISSUE TITLE
Bitbucket commit URL invalid

### ISSUE THREAD

**Issue by ryansonshine** [waderyan/vscode-gitblame#33]
When selecting the `View` button on a commit, the extension opens the URL of `https://bitbucket.org/MyCompany/MyRepo/commit/MyCommitHash` which leads to a 404 page. It should be  `https://bitbucket.org/MyCompany/MyRepo/commits/MyCommitHash`

**Comment by juanjoms** [comment]
The correct repo to open issues is:
https://github.com/Sertion/vscode-gitblame/issues

You can avoid the 404 page in bitbucket with the following steps:
Go to Settings, search for _**Gitblame: Is Web Path Plural**_ and check that option.

More info: https://github.com/Sertion/vscode-gitblame/issues/31
