### ISSUE TITLE
spawn git ENOENT

### ISSUE THREAD

**Issue by zhongzhong0505** [waderyan/vscode-gitblame#35]
git: No such file or directory. (ENOENT)

**Comment by zhongzhong0505** [comment]
![image](https://user-images.githubusercontent.com/15847574/62175436-54af6280-b370-11e9-8fe3-3fd61590894f.png)

**Comment by juanjoms** [comment]
The correct repo to open issues is:
https://github.com/Sertion/vscode-gitblame/issues
