### ISSUE TITLE
No longer visible in status bar

### ISSUE THREAD

**Issue by martellaj** [waderyan/vscode-gitblame#4]
Difficult to pinpoint exactly why, because I updated both Code and Git this morning. I uninstalled/reinstalled the extension with no luck.

* Code version **1.0.0**
* Git version **2.8.1.windows.1**

**Comment by waderyan** [comment]
Strange.. I'll take a look.

**Comment by martellaj** [comment]
Please let me know if you figure something out - I freaking love this extension. I already miss it. :sob:

**Comment by waderyan** [comment]
hey thanks @martellaj I'm wanting to spend some solid time in the next week or two and do a new release. I'll keep you posted.

**Comment by zirtaeb19** [comment]
Having the same issue in Windows 8 and git version 2.7.2.windows.1 hope you can solve it, I really like the extension.

**Comment by stereokai** [comment]
@waderyan For what it's worth, it works on OSX El Capitan with VSCode 1.0.0.

**Comment by ericwooley** [comment]
@waderyan @stereokai It does not work with vscode 1.0.0 with Yosemite

**Comment by martellaj** [comment]
@waderyan So I looked into this a bit this afternoon because I so badly want this extension to work again. I'm getting a `Error: spawn git ENOENT` error from the `gitBlameProcess` call in `gitblame.ts`, but haven't figured out why I'm getting that yet.

**Comment by martellaj** [comment]
So I found out a cause for the `spawn git ENOENT` error is not having Git in your path. Because this extension worked for me in the past and because I can run Git from the command line, I assumed Git was in my path. However, when I gave in and looked, I found that it wasn't there anymore. So I just added the path to `git.exe` to my path and restarted my PC and the extension works again! 

Can't speak to if this is everyone's issue, but for anyone on Windows, you should look here first.

**Comment by waderyan** [comment]
Hey good find @martellaj!

**Comment by martellaj** [comment]
Just for completeness' sake, I checked the status of the extension on my Mac (El Capitan) with VS Code (1.0.0) and the newest version of Git (2.8.1), and it works as expected. You can probably close out this issue!

**Comment by ericwooley** [comment]
na, don't close the issue, I can't upgrade because of corporate whatever, and I am sure tons of people are in the same boat.

**Comment by martellaj** [comment]
@ericwooley Well there's no bug, so it wouldn't make sense to keep it open. Closed issues signify a solution to me. 

But what can't you upgrade? It's actually not an issue with any version I believe. Just need to make sure Git is still in your path.

**Comment by martellaj** [comment]
@ericwooley Nevermind, just saw you're on a Mac running Yosemite. You should clone the repo and run it with the debugger attached - it's very easy to set up.

**Comment by waderyan** [comment]
Just tested this on the latest 1.1 version (publishing now). Should be fixed now.

**Comment by stereokai** [comment]
@waderyan Thank you for keeping us updated

**Comment by isheraz** [comment]
Git Blame not displaying on the sidebar Ubuntu 20.04. VsCode installed from snapstore.
