### ISSUE TITLE
Selecting Git blame in command pallette is showing Hello World

### ISSUE THREAD

**Issue by sandy081** [waderyan/vscode-gitblame#8]
![giphy](https://cloud.githubusercontent.com/assets/10746682/16332938/f9a52bc0-39f8-11e6-8c86-f8ae6ff4864c.gif)

**Comment by martellaj** [comment]
Just out of curiosity, what would you expect it to do there? I understand showing the "Hello world" info bar isn't *helpful*, but what should replace it?

**Comment by jcsrb** [comment]
@martellaj I would expect new file which has the full output of git-blame for the current selected file

**Comment by dpoetzsch** [comment]
I expected something similar to the annotate feature in android studio (see screenshot). Ideally clicking on a blame line would open details on that specific commit where I can also see other changes that happened during that commit.
![screenshot from 2016-07-20 11-30-17](https://cloud.githubusercontent.com/assets/7511464/16981955/8bf3000a-4e6d-11e6-94e8-9bddd8f0fe73.png)

**Comment by waderyan** [comment]
Fixed now. Clicking blame will show the commit id thanks to a PR
